[General]
; Verbosity: Syslog severity levels: 0 -> emerg ... 7 -> debug
__VERBOSE=6

[Directories]
; Base directory where the backups will be stored.
; Can be a directory, a drive letter (e.g., "D:\"), or a network share (e.g., "\\Server\Share").
BACKUP_BASE_DIR=C:\Backups\

; The user-specific subfolder.
; Note: Script variables like ${BACKUP_BASE_DIR} can be reused if defined above.
; Note: Environment variables like %USERNAME% are supported.
BACKUP_USER_BASE_DIR=${BACKUP_BASE_DIR}%USERNAME%\

; The final backup directory.
BACKUP_DIR=${BACKUP_USER_BASE_DIR}%COMPUTERNAME%\

; Directory where the generated job files will be stored.
BACKUP_JOB_DIR=${BACKUP_USER_BASE_DIR}robocopy-jobs\

[Files]
; Path to the robocopy executable.
; If only "robocopy" is specified, the script searches in the Windows PATH.
ROBOCOPY=robocopy

; The directory list file.
BACKUP_DIRLIST=${BACKUP_DIR}dir-list.conf

[Job settings]
JOB_TYPE_SELECTION_MAX_WAITING_TIME_S=30
; Default job type if none is selected.
DEFAULT_JOB_TYPE=Incremental

; Naming schemes for the job files and archives.
JOB_FILE_NAME_SCHEME=*-Job*.RCJ
JOB_LOGFILE_NAME_SCHEME=*-Job*.log

[Archiving settings]
ARCHIVE_NAME_SCHEME=BackupJobs_*.zip
; Maximum number of archives to keep.
MAX_ARCHIVES_COUNT=10

[Logging settings]
BACKUP_LOGFILE=${BACKUP_DIR}Backup.log
; TODO: Use for errors (and warnings?)
ERROR_LOGFILE=${BACKUP_DIR}Error.log

; Logs more detailed messages when enabled.
ENABLE_TRACE_LOG=true
;TRACE_LOG_LOCAL_DIR=${BACKUP_DIR}
TRACE_LOGFILE_NAME=Trace.log
UPLOAD_TRACE_TO_BACKUP_DIR=true
