[General]
; Verbosity: Syslog severity levels: 0 -> emerg ... 7 -> debug
; Highest value to see all messages in this basic smoke-test.
__VERBOSE=7

[Mandatory directories]
; remove  BACKUP_TEMPLATES_DIR=${SCRIPT_DIR}templates\

[Directories]
BACKUP_BASE_DIR=${SCRIPT_DIR}destination\
BACKUP_USER_BASE_DIR=${BACKUP_BASE_DIR}testuser\
BACKUP_DIR=${BACKUP_USER_BASE_DIR}%COMPUTERNAME%\
BACKUP_JOB_DIR=${BACKUP_USER_BASE_DIR}robocopy-jobs\

[Files]
ROBOCOPY=robocopy

BACKUP_DIRLIST=${SCRIPT_DIR}smoke-test-dir-list.conf
; For smoke-test: special case where $BACKUP_LOGFILE is not in $BACKUP_DIR.
BACKUP_LOGFILE=${SCRIPT_DIR}logdir\Backup.log
ERROR_LOGFILE=${BACKUP_DIR}Error.log

[Job settings]
; For smoke-test: No waiting
JOB_TYPE_SELECTION_MAX_WAITING_TIME_S=0
DEFAULT_JOB_TYPE=Incremental

JOB_FILE_NAME_SCHEME=${COMPUTERNAME}-Job*.RCJ
JOB_LOGFILE_NAME_SCHEME=${COMPUTERNAME}-Job*.log

[Archiving settings]
ARCHIVE_NAME_SCHEME=${COMPUTERNAME}-Jobs-*.zip
MAX_ARCHIVES_COUNT=5

[Robocopy settings]

[Logging settings]
; Logs more detailed messages when enabled.
ENABLE_TRACE_LOG=true
;TRACE_LOG_LOCAL_DIR=${BACKUP_DIR}
TRACE_LOGFILE_NAME=Trace.log
UPLOAD_TRACE_TO_BACKUP_DIR=true
