[General]
; Highest value to see all messages in this basic smoke-test.
__VERBOSE=7

[Directories]
BACKUP_BASE_DIR=${SCRIPT_DIR}destination\
; For smoke-test: fixed values "testuser" and "testcomputer"
BACKUP_USER_BASE_DIR=${BACKUP_BASE_DIR}testuser\
BACKUP_DIR=${BACKUP_USER_BASE_DIR}testcomputer\
BACKUP_JOB_DIR=${BACKUP_USER_BASE_DIR}robocopy-jobs\

[Files]
ROBOCOPY=robocopy

BACKUP_DIRLIST=${BACKUP_DIR}dir-list.conf

[Job settings]
; For smoke-test: No waiting
JOB_TYPE_SELECTION_MAX_WAITING_TIME_S=0
DEFAULT_JOB_TYPE=Incremental

; For smoke-test: fixed value "testcomputer"
JOB_FILE_NAME_SCHEME=testcomputer-Job*.RCJ
JOB_LOGFILE_NAME_SCHEME=testcomputer-Job*.log

[Archiving settings]
; For smoke-test: fixed value "testcomputer"
ARCHIVE_NAME_SCHEME=testcomputer-Jobs-*.zip
MAX_ARCHIVES_COUNT=5

[Logging settings]
; For smoke-test: special case where $BACKUP_LOGFILE is not in $BACKUP_DIR.
BACKUP_LOGFILE=${SCRIPT_DIR}logdir\Backup.log
ERROR_LOGFILE=${SCRIPT_DIR}logdir\Error.log

; Logs more detailed messages when enabled.
ENABLE_TRACE_LOG=true
;TRACE_LOG_LOCAL_DIR=${BACKUP_DIR}
TRACE_LOGFILE_NAME=Trace.log
UPLOAD_TRACE_TO_BACKUP_DIR=true
